parameters:
- name: jobDisplayName
  default: ''
- name: appName
  default: ''
- name: azServicePrincipal
  default: ''
- name: azKeyVaultName
  default: ''
- name: sonarCloud
  default: ''
- name: sonarOrg
  default: ''
- name: sonarProjectKey
  default: ''
- name: sonarProjectName
  default: ''

jobs:
- job:
  displayName: ${{ parameters.jobDisplayName }} # Template Parameter
  variables:
    dotNetVersion: 8.0.412
    buildConfiguration: Release
    entryProject: $(Build.Repository.LocalPath)/${{ parameters.appName }}/${{ parameters.appName }}.csproj
    outputDirectory: $(Build.ArtifactStagingDirectory)/output

  steps:
    - task: AzureKeyVault@2
      displayName: Access Azure Key Vault
      inputs:
        azureSubscription: ${{ parameters.azServicePrincipal }} # Template Parameter
        KeyVaultName: ${{ parameters.azKeyVaultName }} # Template Parameter

    - task: UseDotNet@2
      displayName: Install Dotnet
      inputs:
        version: $(dotNetVersion)   # ✅ This now uses the pinned 6.0.414 version

    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: Replace tokens
      inputs:
        rootDirectory: $(Pipeline.Workspace) # Runtime Variable
        tokenPattern: custom
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        targetFiles: |
          **/appsettings.json
          **/NuGet.Config

    - task: AdvancedSecurity-Codeql-Init@1
      displayName: Advance Security Init
      inputs:
        languages: csharp

    - task: AdvancedSecurity-Dependency-Scanning@1
      displayName: Advance Security Dependency Scan

    - task: AdvancedSecurity-Codeql-Autobuild@1
      displayName: Advance Security Build Scan

    - task: AdvancedSecurity-Codeql-Analyze@1
      displayName: Advance Security Analyze

    - task: SonarCloudPrepare@1
      displayName: Sonar Prepare
      inputs:
        SonarCloud: ${{ parameters.sonarCloud }} # Template Parameter
        organization: ${{ parameters.sonarOrg }} # Template Parameter
        scannerMode: MSBuild
        projectKey: ${{ parameters.sonarProjectKey }} # Template Parameter
        projectName: ${{ parameters.sonarProjectName }} # Template Parameter
        extraProperties: |
          sonar.exclusions=**/obj/**,**/bin/**,**/*.dll

    - task: UseDotNet@2
      displayName: Install Dotnet
      inputs:
        version: $(dotNetVersion) # Inline Variable

    - task: DotNetCoreCLI@2
      displayName: Dotnet Restore
      inputs:
        command: restore
        arguments: -c $(buildConfiguration)  # Inline Variable

    - task: DotNetCoreCLI@2
      displayName: Dotnet Build
      inputs:
        command: build
        arguments: -c $(buildConfiguration)  # Inline Variable

    - task: DotNetCoreCLI@2
      displayName: Dotnet Test
      inputs:
        command: test
        arguments: -c $(buildConfiguration)  # Inline Variable

    - task: SonarCloudAnalyze@1
      displayName: Sonar Analyze

    - task: SonarCloudPublish@1
      displayName: Sonar Publish
      inputs:
        pollingTimeoutSec: 300

    - task: DotNetCoreCLI@2
      displayName: Dotnet Publish
      inputs:
        command: publish
        arguments: $(entryProject) -c $(buildConfiguration) -o $(outputDirectory)  # Inline Variable
        modifyOutputPath: true
        zipAfterPublish: true
        publishWebProjects: false

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: $(outputDirectory)  # Inline Variable
        ArtifactName: drop
        publishLocation: Container